<?php

namespace App\Models\Customer;

use App\Enums\GenderEnum;
use App\Models\Sale\SaleRow;
use App\Models\Scopes\StructureScope;
use App\Models\Traits\HasStructure;
use Illuminate\Database\Eloquent\Attributes\ScopedBy;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Customer extends Model
{
    /** @use HasFactory<\Database\Factories\Customer\CustomerFactory> */
    use HasFactory, HasStructure, SoftDeletes;

    protected $fillable = [
        'structure_id',
        'user_id',
        'uuid',
        'first_name',
        'last_name',
        'birth_date',
        'gender',
        'birthplace',
        'tax_id_code',
        'email',
        'phone',
        'street',
        'number',
        'city',
        'zip',
        'province',
        'country',

        // Additional fields for GDPR and marketing consents
        'gdpr_consent',
        'gdpr_consent_at',
        'marketing_consent',
        'marketing_consent_at',
        'photo_consent',
        'medical_data_consent',
        'data_retention_until',
    ];

    protected $casts = [
        'birth_date' => 'date',
        'gender' => GenderEnum::class,
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $model->uuid = (string) \Illuminate\Support\Str::uuid();
        });
    }

    public function getOptionLabelAttribute()
    {
        return $this->first_name . ' ' . $this->last_name . ' (' . $this->birth_date->format('d/m/Y') . ')';
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function user()
    {
        return $this->belongsTo(\App\Models\CentralUser::class, 'user_id');
    }

    public function subscriptions()
    {
        // Get the subscriptions for the customer where the type is 'subscription'
        return $this->hasMany(CustomerSubscription::class)
            ->where('type', 'subscription');
    }

    public function active_subscriptions()
    {
        return $this->subscriptions()
            ->where('start_date', '<=', now())
            ->where(function ($query) {
                $query->whereNull('end_date')
                    ->orWhere('end_date', '>=', now());
            });
    }

    public function past_subscriptions()
    {
        return $this->subscriptions()
            ->where('end_date', '<', now());
    }

    public function memberships()
    {
        return $this->hasMany(CustomerSubscription::class)
            ->where('type', 'membership');
    }

    public function active_membership()
    {
        return $this->hasOne(CustomerSubscription::class)
            ->where('start_date', '<=', now())
            ->where(function ($query) {
                $query->whereNull('end_date')
                    ->orWhere('end_date', '>=', now());
            });
    }

    public function last_membership()
    {
        return $this->hasOne(CustomerSubscription::class)
            ->where('type', 'membership')
            ->orderBy('end_date', 'desc');
    }

    public function sales()
    {
        return $this->hasMany(\App\Models\Sale\Sale::class)
            ->orderBy('date', 'desc')
            ->orderBy('progressive_number', 'desc');
    }

    public function getSalesSummaryAttribute()
    {
        $sales = $this->sales()->with(['rows', 'payments'])->get();

        $sale_count = $sales->count();
        $total_amount = 0;
        $payed = 0;
        $not_payed = 0;
        $expired = 0;
        $total_sale_products = 0;

        foreach ($sales as $sale) {
            $sale_total = $sale->rows->sum('total');
            $paidAmount = $sale->payments->sum('amount');
            $notPaidAmount = $sale_total - $paidAmount;

            $total_amount += $sale_total;
            $payed += $paidAmount;
            $not_payed += max(0, $notPaidAmount);
            $total_sale_products += $sale->rows->sum('quantity');

            if (isset($sale->due_date) && $sale->due_date && $sale->due_date->isPast() && $notPaidAmount > 0) {
                $expired += $notPaidAmount;
            }
        }

        return [
            'sale_count'           => $sale_count,
            'total_amount'         => $total_amount,
            'payed'                => $payed,
            'not_payed'            => $not_payed,
            'expired'              => $expired,
            'total_sale_products'  => $total_sale_products,
        ];
    }

    public function medical_certifications()
    {
        return $this->morphMany(
            \App\Models\Support\MedicalCertification::class,
            'medical_certifiable',
            'medical_certifiable_type',
            'medical_certifiable_id'
        );
    }

    public function last_medical_certification()
    {
        return $this->morphOne(
            \App\Models\Support\MedicalCertification::class,
            'medical_certifiable',
            'medical_certifiable_type',
            'medical_certifiable_id'
        )->latest();
    }
}
