<?php

namespace App\Models\Customer;

use App\Enums\GenderEnum;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    /** @use HasFactory<\Database\Factories\Customer\CustomerFactory> */
    use HasFactory;

    protected $fillable = [
        'uuid',
        'first_name',
        'last_name',
        'birth_date',
        'gender',
        'birthplace',
        'tax_id_code',
        'email',
        'phone',
        'street',
        'number',
        'city',
        'zip',
        'province',
        'country',
    ];

    protected $casts = [
        'birth_date' => 'date',
        'gender' => GenderEnum::class,
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $model->uuid = (string) \Illuminate\Support\Str::uuid();
        });
    }

    public function getOptionLabelAttribute()
    {
        return $this->first_name . ' ' . $this->last_name . ' (' . $this->birth_date->format('d/m/Y') . ')';
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}
