<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubscriptionPlan extends Model
{
    /** @use HasFactory<\Database\Factories\SubscriptionPlanFactory> */
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'description',
        'price',
        'currency',
        'interval',
        'trial_days',
        'tier',
        'is_trial_plan',
        'sort_order',
        'is_active',
        'stripe_price_id',
    ];

    protected $casts = [
        'price' => 'integer', // Stored as cents
        'trial_days' => 'integer',
        'sort_order' => 'integer',
        'is_active' => 'boolean',
        'is_trial_plan' => 'boolean',
        'tier' => \App\Enums\SubscriptionPlanTier::class,
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $model->slug = str($model->name)->slug();
        });
    }

    public function tenants()
    {
        return $this->belongsToMany(
            Tenant::class,
            'subscription_plan_tenant',
            'subscription_plan_id',
            'tenant_id'
        )->withPivot(['is_active', 'trial_ends_at', 'ends_at'])
            ->using(SubscriptionPlanTenant::class);
    }

    /**
     * Features included or available in this plan.
     */
    public function features()
    {
        return $this->belongsToMany(PlanFeature::class, 'subscription_plan_features')
            ->withPivot(['is_included', 'quota_limit', 'price_cents'])
            ->withTimestamps();
    }

    /**
     * Only features included in this plan.
     */
    public function includedFeatures()
    {
        return $this->features()->wherePivot('is_included', true);
    }

    /**
     * Features available as addons for this plan.
     */
    public function addonFeatures()
    {
        return $this->features()->wherePivot('is_included', false);
    }

    /**
     * Scope: Active plans only.
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope: Order by tier.
     */
    public function scopeOrderByTier($query)
    {
        return $query->orderBy('sort_order', 'asc');
    }

    /**
     * Scope: By tier.
     */
    public function scopeByTier($query, string $tier)
    {
        return $query->where('tier', $tier);
    }
}
